/**
 * Build every app icon from a single source.
 * Run: npm run icons
 *
 * Mark: "shield and voice" - a gold shield with a cream microphone on a black background.
 * Every icon (install, tab, header) is that one fixed mark and does not change
 * with the app palettes (decision D13 in docs/PLAN.md). Only UI colors
 * (buttons, navigation, progress) come from the palettes.
 *
 * Outputs (all in public/, all local):
 *   icon.svg                 vector mark for modern browser favicons
 *   favicon.ico              16, 32 and 48 versions for older browsers and the Windows bar
 *   apple-touch-icon.png     180x180 for adding to an iOS home screen
 *   pwa-192x192.png          Android install icon
 *   pwa-512x512.png          install icon and splash image
 *   pwa-maskable-512.png     maskable version with an 80% safe area
 *
 * In addition, a preview sheet is written to .cache/brand-preview.png so the
 * mark can be checked by eye at real sizes (512 down to 16 pixels).
 * It has no external dependency and runs fully offline.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { APP_ICON, MASKABLE_SCALE, brandGeometry, brandSvg } from '../src/lib/brand.mjs';
import { encodeICO, encodePNG, parsePath, rasterize } from './lib/raster.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PUBLIC = join(ROOT, 'public');
const CACHE = join(ROOT, '.cache');

/** Mark shapes (without the background) in paint order, in a 512x512 coordinate system */
function markShapes(size) {
  const g = brandGeometry(size);
  return [
    {
      kind: 'stroke',
      subs: parsePath(g.shield),
      width: g.shieldWidth,
      color: APP_ICON.shield,
    },
    ...g.mic.map((p) => ({
      kind: 'stroke',
      subs: parsePath(p.d),
      width: p.width,
      color: APP_ICON.mic,
    })),
  ];
}

/** Mark on a rounded tile (for the favicon and install icons with transparent corners) */
function tileShapes(size) {
  const g = brandGeometry(size);
  return [{ kind: 'tile', size: g.tile, radius: g.radius, color: APP_ICON.bg }, ...markShapes(size)];
}

/** Mark on a flat background with no rounded corners (maskable and iOS) */
function bleedShapes(size) {
  return [{ kind: 'bg', color: APP_ICON.bg }, ...markShapes(size)];
}

function pngFor(size, opts = {}) {
  return encodePNG(rasterize(size, opts.bleed ? bleedShapes(size) : tileShapes(size), opts));
}

/* ------------------------------------------------------------------ */
/* 1) Vector version (SVG)                                            */
/* ------------------------------------------------------------------ */

function buildSvg() {
  /* The install icon is always the fixed global version; the tab favicon uses the same fixed mark */
  return (
    `<!-- Generated by "npm run icons" from src/lib/brand.mjs; do not edit by hand -->\n` +
    brandSvg({ tile: APP_ICON.bg }) +
    '\n'
  );
}

/* ------------------------------------------------------------------ */
/* 2) Preview sheet (for visual review, not committed to the repo)   */
/* ------------------------------------------------------------------ */

function paste(target, img, x, y) {
  for (let r = 0; r < img.height; r++) {
    for (let c = 0; c < img.width; c++) {
      const si = (r * img.width + c) * 4;
      const di = ((y + r) * target.width + (x + c)) * 4;
      const a = img.data[si + 3] / 255;
      target.data[di] = Math.round(img.data[si] * a + target.data[di] * (1 - a));
      target.data[di + 1] = Math.round(img.data[si + 1] * a + target.data[di + 1] * (1 - a));
      target.data[di + 2] = Math.round(img.data[si + 2] * a + target.data[di + 2] * (1 - a));
      target.data[di + 3] = 255;
    }
  }
}

function buildPreview() {
  const sizes = [512, 192, 48, 32, 16];
  const gap = 40;
  const width = sizes.reduce((a, s) => a + s, 0) + gap * (sizes.length + 1);
  const height = 512 + gap * 2;
  const sheet = { width, height, data: new Uint8Array(width * height * 4) };
  /* App paper background so the real contrast is visible */
  const paper = [0xf4, 0xf0, 0xe6];
  for (let i = 0; i < sheet.data.length; i += 4) {
    sheet.data[i] = paper[0];
    sheet.data[i + 1] = paper[1];
    sheet.data[i + 2] = paper[2];
    sheet.data[i + 3] = 255;
  }
  let x = gap;
  for (const s of sizes) {
    paste(sheet, rasterize(s, tileShapes(s)), x, height - gap - s);
    x += s + gap;
  }
  return encodePNG(sheet);
}

/** Mapping factor when the mark has to fill part of the canvas (safe area) */
const fitScale = (size, fraction) => (size * fraction) / 512;

/* ------------------------------------------------------------------ */
/* 3) Run                                                             */
/* ------------------------------------------------------------------ */

mkdirSync(PUBLIC, { recursive: true });
mkdirSync(CACHE, { recursive: true });

const outputs = [
  ['icon.svg', Buffer.from(buildSvg(), 'utf8')],
  /* iOS applies its own rounded mask, so use a flat background with no rounded corners and a safe margin */
  ['apple-touch-icon.png', pngFor(180, { bleed: true, scale: fitScale(180, 0.8) })],
  ['pwa-192x192.png', pngFor(192)],
  ['pwa-512x512.png', pngFor(512)],
  /* maskable: the mark sits inside the 80% safe area and the background is flat so Android cropping cuts nothing */
  ['pwa-maskable-512.png', pngFor(512, { bleed: true, scale: fitScale(512, MASKABLE_SCALE) })],
  [
    'favicon.ico',
    encodeICO([
      { size: 16, png: pngFor(16) },
      { size: 32, png: pngFor(32) },
      { size: 48, png: pngFor(48) },
    ]),
  ],
];

for (const [name, buf] of outputs) {
  writeFileSync(join(PUBLIC, name), buf);
  console.log(`[icon] public/${name}  ${(buf.length / 1024).toFixed(1)} KiB`);
}

writeFileSync(join(CACHE, 'brand-preview.png'), buildPreview());
console.log('[icon] .cache/brand-preview.png  (visual check 512 down to 16 px)');
